//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrishiJagarnDigitalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CropDetail
    {
        public CropDetail()
        {
            this.FormerDetails = new HashSet<FormerDetail>();
        }
    
        public int id { get; set; }
        public string CropName { get; set; }
        public string CropVariety { get; set; }
        public string CropSeasion { get; set; }
    
        public virtual ICollection<FormerDetail> FormerDetails { get; set; }
    }
}
//https://localhost:44316/Models/CropDetail.cs;