//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrishiJagarnDigitalSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KrishiEntities : DbContext
    {
        public KrishiEntities()

          : base("name=KrishiEntities")

        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CropDetail> CropDetails { get; set; }
        public DbSet<CropePriceDetail> CropePriceDetails { get; set; }
        public DbSet<FormerDetail> FormerDetails { get; set; }
        public DbSet<UserRegistration> UserRegistrations { get; set; }
    }
}
