//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrishiJagarnDigitalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegistration
    {
        public int id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email_id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Contect_No { get; set; }
    }
}
